Retea neuronala pentru $y= x_1 \text{XNOR} x_2$ 

In [1]:
import numpy as np
def g(z):
    a=(1+np.exp(-z))
    return 1/a

In [2]:
def ANDD(x1,x2):
    x=np.array([1, x1, x2])
    x=x.reshape(-1, 1)
    teta=np.array([-30, 20, 20])
    return int(g(teta.dot(x))>0.5)

In [3]:
def NAN(x1,x2):
    x=np.array([1, x1, x2])
    x=x.reshape(-1, 1)
    teta=np.array([10, -20, -20])
    return int(g(teta.dot(x))>0.5)

In [4]:
def ORR(x1,x2):
    x=np.array([1, x1, x2])
    x=x.reshape(-1, 1)
    teta=np.array([-10, 20, 20])
    return int(g(teta.dot(x))>0.5)

In [5]:
for x1 in range(2):
    for x2 in range(2):
        print(x1, x2, ORR(ANDD(x1,x2),NAN(x1,x2)))

0 0 1
0 1 0
1 0 0
1 1 1


In [17]:
teta=np.array([np.array([[-30, 20, 20],[10, -20, -20]]),np.array([-10, 20, 20])])

teta

array([array([[-30,  20,  20],
       [ 10, -20, -20]]),
       array([-10,  20,  20])], dtype=object)

In [21]:
print(teta[0])  #teta[0] e matricea de greutati de pe primul layer

[[-30  20  20]
 [ 10 -20 -20]]


In [74]:
x1=0
x2=0
x=np.array([])
a=np.array([])
teta=np.array([])

x=np.array([1,x1,x2])

teta1=np.array([[-30, 20, 20],[10, -20, -20]])
teta2=np.array([-10, 20, 20])
teta[1]=
teta=np.array([teta1,teta2])
z2=teta[0].dot(x)
a2=g(z2)
a2=np.hstack((np.array([1]),a2))   #fa asta intr-o functie si fa for pe layer si for in layer
z3=teta[1].dot(a2)
a3=g(z3)
a3

0.9999545608951235